services:
  - type: web
    name: k-ai-pharma
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: API_KEY
        value: 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
      - key: LLM_PROVIDER
        value: openai
      - key: LLM_NAME
        value: meta-llama/llama-3.2-3b-instruct:free
      - key: OPENAI_BASE_URL
        value: https://openrouter.ai/api/v1
      - key: MONGO_URI
        fromDatabase:
          name: k-ai-mongo
          property: connectionString
      - key: CELERY_BROKER_URL
        fromDatabase:
          name: k-ai-redis
          property: connectionString
      - key: CELERY_RESULT_BACKEND
        fromDatabase:
          name: k-ai-redis
          property: connectionString
      - key: CACHE_REDIS_URL
        fromDatabase:
          name: k-ai-redis
          property: connectionString

databases:
  - name: k-ai-mongo
    databaseName: k-ai
    user: k-ai-user
  - name: k-ai-redis